# Generated by Django 4.2.18 on 2025-01-24 17:14

import Student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='photo',
            field=models.ImageField(upload_to=Student.models.student_directory_path),
        ),
    ]
